name: Schedule Test

on:
  schedule:
    - cron: "33 15 * * *"
      timezone: "Europe/Zurich"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Schedule testen
        run: |
          echo "Schedule funktioniert"
          date
